version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    env_file:
      - .env
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: flask_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
